FROM python3.5

RUN apt-get update 
  && apt-get clean 
  && rm -rf varlibaptlists tmp vartmp


RUN groupadd -g 799 nyu && 
    useradd -r -u 999 -g nyu nyu

# Set up a working folder and install the pre-reqs
WORKDIR app

USER nyu

COPY --chown=nyunyu . .

CMD [ python, ./authoritative_server.py ]